import { Product } from "@/types/types";

export const products: Product[] = [
  {
    id: 1,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "fruit",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 2,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "vegetable",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 3,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "fruit",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 4,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "fruit",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 5,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "vegetable",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 6,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "fruit",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 7,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "fruit",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 8,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "fruit",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 9,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "fruit",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 10,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "vegetable",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 11,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "vegetable",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 12,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "vegetable",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 13,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "vegetable",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 14,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "vegetable",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 15,
    name: "Banan fruits Banan fruitsBanan fruitsBanan fruitsBanan fruits",
    category: "vegetable",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
    price: 100,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 15,
    unit: "kg",
    discount: 10,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 1,
      packageWidth: 1,
      packageLength: 1,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Red",
        price: 100,
      },
      {
        id: 2,
        name: "Green",
        price: 100,
      },
      {
        id: 3,
        name: "Yellow",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 10,
    tags: ["fruit", "vegetable"],
  },
  {
    id: 16,
    name: "Fresh Apples Fresh Apples Fresh Apples Fresh Apples",
    category: "fruit",
    description: "Delicious and crispy apples, perfect for snacking or baking. A source of essential vitamins and minerals for a healthy lifestyle.",
    price: 150,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 20,
    unit: "kg",
    discount: 5,
    rating: 4.8,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 2,
      packageHeight: 3,
      packageWidth: 4,
      packageLength: 2,
      shippingFee: 15000,
    },
    variants: [
      {
        id: 1,
        name: "Small",
        price: 140,
      },
      {
        id: 2,
        name: "Medium",
        price: 150,
      },
      {
        id: 3,
        name: "Large",
        price: 160,
      },
    ],
    shop: {
      id: 2,
      name: "Shop 2",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "bandung",
      shippingChannel: ["JNE", "Pos Indonesia", "GoSend"],
    },
    sold: 25,
    tags: ["apple", "fruit"],
  },
  {
    id: 17,
    name: "Juicy Mangoes Juicy Mangoes Juicy Mangoes Juicy Mangoes",
    category: "fruit",
    description: "Sweet and juicy mangoes straight from the farm. Great for smoothies, desserts, or enjoying fresh.",
    price: 120,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 30,
    unit: "kg",
    discount: 15,
    rating: 4.7,
    isWishlist: true,
    shippingInfo: {
      packageWeight: 1.5,
      packageHeight: 2,
      packageWidth: 2,
      packageLength: 3,
      shippingFee: 12000,
    },
    variants: [
      {
        id: 1,
        name: "Small",
        price: 110,
      },
      {
        id: 2,
        name: "Medium",
        price: 120,
      },
      {
        id: 3,
        name: "Large",
        price: 130,
      },
    ],
    shop: {
      id: 3,
      name: "Shop 3",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "surabaya",
      shippingChannel: ["J&T", "Ninja Express", "TIKI"],
    },
    sold: 50,
    tags: ["mango", "fruit"],
  },
  {
    id: 18,
    name: "Organic Carrots Organic Carrots Organic Carrots",
    category: "vegetable",
    description: "Crunchy and fresh organic carrots, perfect for salads, stews, or as a healthy snack.",
    price: 90,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 50,
    unit: "kg",
    discount: 0,
    rating: 4.6,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 3,
      packageHeight: 5,
      packageWidth: 3,
      packageLength: 4,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Regular",
        price: 90,
      },
      {
        id: 2,
        name: "Organic",
        price: 100,
      },
    ],
    shop: {
      id: 1,
      name: "Shop 1",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "jakarta",
      shippingChannel: ["JNE", "J&T", "Ninja Express"],
    },
    sold: 30,
    tags: ["carrot", "vegetable"],
  },
  {
    id: 19,
    name: "Golden Potatoes Golden Potatoes Golden Potatoes",
    category: "vegetable",
    description: "Rich and flavorful golden potatoes, versatile for any dish from mashed to roasted.",
    price: 110,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 60,
    unit: "kg",
    discount: 10,
    rating: 4.3,
    isWishlist: true,
    shippingInfo: {
      packageWeight: 4,
      packageHeight: 4,
      packageWidth: 4,
      packageLength: 5,
      shippingFee: 15000,
    },
    variants: [
      {
        id: 1,
        name: "Small",
        price: 100,
      },
      {
        id: 2,
        name: "Medium",
        price: 110,
      },
    ],
    shop: {
      id: 2,
      name: "Shop 2",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "bandung",
      shippingChannel: ["JNE", "TIKI", "Ninja Express"],
    },
    sold: 40,
    tags: ["potato", "vegetable"],
  },
  {
    id: 20,
    name: "Ripe Bananas Ripe Bananas Ripe Bananas",
    category: "fruit",
    description: "Sweet and ripe bananas, a perfect snack or ingredient for your favorite desserts.",
    price: 80,
    imageUrl: [
      "https://fastly.picsum.photos/id/44/200/200.jpg?hmac=W5KcqhapHjBgEIHGQpQnX6o9jdOXQEVCKEdGIohjisY",
      "https://fastly.picsum.photos/id/243/200/200.jpg?hmac=fW5ZwzzyTBy2t2MROp988oq12mZnKwN0coFLhZEE87s",
      "https://fastly.picsum.photos/id/532/200/200.jpg?hmac=PPwpqfjXOagQmhd_K7H4NXyA4B6svToDi1IbkDW2Eos",
    ],
    stocks: 35,
    unit: "kg",
    discount: 5,
    rating: 4.5,
    isWishlist: false,
    shippingInfo: {
      packageWeight: 1,
      packageHeight: 2,
      packageWidth: 2,
      packageLength: 3,
      shippingFee: 10000,
    },
    variants: [
      {
        id: 1,
        name: "Small",
        price: 70,
      },
      {
        id: 2,
        name: "Large",
        price: 80,
      },
    ],
    shop: {
      id: 3,
      name: "Shop 3",
      imageUrl: "https://fastly.picsum.photos/id/354/200/200.jpg?hmac=ykMwenrB5tcaT_UHlYwh2ZzAZ4Km48YOmwJTFCiodJ4",
      addressCity: "surabaya",
      shippingChannel: ["TIKI", "J&T", "Ninja Express"],
    },
    sold: 20,
    tags: ["banana", "fruit"],
  },
];
