import type { Metadata } from "next";
import { poppins, playfairDisplay } from "@/interfaces/fonts/fonts";
import "@/styles/globals.css";
import HeaderWrapper from "@/interfaces/components/global/header/HeaderWrapper";
import Footer from "@/interfaces/components/global/footer/Footer";
import { CartProvider } from "@/hooks/cart/CartContext";
import { ScreenSizeProvider } from "@/hooks/cart/ScreenSizeProvider";

export const metadata: Metadata = {
  title: "Arva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${playfairDisplay.variable}`}>
      <body className="w-screen min-h-screen antialiased overflow-x-hidden">
        <ScreenSizeProvider>
          <CartProvider>
            <HeaderWrapper />
            {children}
            <Footer />
          </CartProvider>
        </ScreenSizeProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
